### ISSUE TITLE
Detail page frame component.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-app#146]
To build a common component for the second type of detail page, check the demo below.
This is a common component so don't need to implement the page content in the panel, just the frame with background (semi-transparent) on the top and back button. 

<img width="1440" alt="Screen Shot 2021-10-12 at 5 49 23 PM" src="https://user-images.githubusercontent.com/5744708/136933927-47dfdd46-6b99-414e-844f-c15292ba572d.png">

Reference: 

https://github.com/Greenstand/treetracker-wallet-web/issues/38

---

Some hints for building components:

- Our Figma design is here: https://www.figma.com/file/XtReDuYYGDVQBv4JfzVG0g/Greenstand---Wallet?node-id=7%3A71
- A tutorial of how to use Cypress component tool to build components: https://github.com/Greenstand/treetracker-wallet-web#how-to-build-a-component
- We are using MaterialUI to build the app: https://material-ui.com/
- When you are ready to raise PR for the component, please attach the screenshot of the component for review.
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by dtabarini** [comment]
I would like to take this!

**Comment by dadiorchen** [comment]
@rgesulfo I'm confused by this, we seems to have to different version of the UI on figma?
This is the stale version: https://www.figma.com/file/XtReDuYYGDVQBv4JfzVG0g/Greenstand---Wallet?node-id=7%3A71

**Comment by dtabarini** [comment]
@rgesulfo Can I be added to the figma? The link says I do not have access
