### ISSUE TITLE
Integrate the page: planter details

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-app#149]
Prerequisites: #146 

Integrate the whole page with: components, API calls, if necessary, please add some mock data in the spec file.
Please write integration test covering this page, as guided in the readme's test section.

<img width="1440" alt="Screen Shot 2021-10-13 at 11 23 15 AM" src="https://user-images.githubusercontent.com/5744708/137061839-514abd21-a8c4-48ef-b127-41b1905a7ced.png">

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-wallet-web#treetracker-impact-wallet) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by dadiorchen** [comment]
@dtabarini did you get any progress on this?

**Comment by dtabarini** [comment]
Yeah still working on it!

**Comment by dadiorchen** [comment]
Great, pleaes checkout newest code, I have made some progress on filling those information fields, note we are migrate to use the mock-server in : treetracer-web-map-client, in short, these two app will use the same API service.

**Comment by dadiorchen** [comment]
https://github.com/Greenstand/treetracker-wallet-web/issues/170

**Comment by dadiorchen** [comment]
@dtabarini have to quit this issue for personal reason, so this issue now is open for everyone.
