### ISSUE TITLE
Implement the planter page

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-app#170]
Check the video:

https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202021-11-17%20at%205.36.53%20PM.mp4

![image](https://user-images.githubusercontent.com/5744708/142176858-36dcd2b3-757d-4eec-9624-69c1bdd76559.png)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-wallet-web#treetracker-impact-wallet) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by tobytao1** [comment]
I would like to take this, but the link above is error as I clicked in.

**Comment by dadiorchen** [comment]
@tobytao1 I have fixed the link

**Comment by dadiorchen** [comment]
This issue now is open to everyone!

**Comment by sunnyjain15699** [comment]
Yo! I would like to work on this issue ?

**Comment by dadiorchen** [comment]
Good!

**Comment by sunnyjain15699** [comment]
Hi @dadiorchen! Can you add me in your slack community. My email is sunnypersonal15699@gmail.com

**Comment by dadiorchen** [comment]
@sunnyjain15699 I have invited you
