### ISSUE TITLE
Add data for PlanterList component

### ISSUE THREAD

**Issue by VWRoli** [Greenstand/treetracker-wallet-app#198]
PlanterList component should get the data from the API. 

![Screenshot from 2021-12-14 16-28-51](https://user-images.githubusercontent.com/31432331/146028231-c0850237-82fb-4c27-8fc5-f4d4743c8ea8.png)

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-wallet-web#treetracker-impact-wallet) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.
- More issues in this project: https://github.com/orgs/Greenstand/projects/28

**Comment by VWRoli** [comment]
I'm pretty much done with this @dadiorchen. 
One problem is that the tree species data does not have an image src. Should I add this to the API? Will there be images for tree species in the real API?
![Screenshot from 2021-12-14 16-47-43](https://user-images.githubusercontent.com/31432331/146031651-55d8b836-1508-4303-9e0c-4f47ef0b2076.png)

**Comment by dadiorchen** [comment]
@VWRoli thanks for progress on this, we don't have a formal profile image for species, but I'm thinking maybe we can make a workaround in some way, so you can assume that we do provide it now. 
But the way, do you think we can make a good image-cutting job through that image service? The service we used for image thumbnail? 
for example: if we want to cut these images below to the size as shown as in the design
https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2020.11.24.08.43.59_8.460146666666667_-13.187863333333333_ba12ef4e-15ac-4c0d-93e7-948fd7175e38_IMG_20201117_115746_1101650499.jpg
https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2020.11.24.08.43.33_8.459181666666666_-13.188356666666667_309e8902-e71e-4125-9d58-354dda6bb3f2_IMG_20201117_113327_2007420735.jpg

**Comment by VWRoli** [comment]
> But the way, do you think we can make a good image-cutting job through that image service?  The service we used for image thumbnail? for example: if we want to cut these images below to the size as shown as in the design 

As in resizing to a smaller size? Sure, we had no trouble with that service so far.
