### ISSUE TITLE
Implement Onboarding mobile UI Screens Design

### ISSUE THREAD

**Issue by pierrelstan** [Greenstand/treetracker-wallet-app#215]
# Description:
We need a user interface for our onboarding feature that guides users through a series of three screens to introduce our app. The goal of this issue is to design and implement a visually appealing and user-friendly Onboard UI.

## Acceptance Criteria:
 Each screen displays correctly with the following elements:
- [ ] Logo
- [ ] Image or illustration
- [ ] Description text 
Login and Sign Up buttons

Progress indicator
- [ ] The UI is responsive and works well on different mobile screen sizes

Attachments:
[Figma design](https://www.figma.com/design/UjbBQIFKATd1DisTBRsMdd/Test-Project?node-id=29-9854&t=9h97AC3WcxkziHnS-0)

![Image](https://github.com/user-attachments/assets/6b7b7035-4b97-4e5a-9235-3c4eedba62ab)
![Image](https://github.com/user-attachments/assets/b75be7df-746b-4068-a85f-d6868c32d595)
![Image](https://github.com/user-attachments/assets/cd63e26f-99c5-444d-a2c4-82ab83be727e)

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-wallet-app) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/design/UjbBQIFKATd1DisTBRsMdd/Test-Project?node-id=29-9854&t=9h97AC3WcxkziHnS-0)
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by khaihtruong** [comment]
I'm interested in this issue!
