### ISSUE TITLE
Implement Web Login UI design

### ISSUE THREAD

**Issue by pierrelstan** [Greenstand/treetracker-wallet-app#219]
# Description:
We need a user interface for our login feature. The goal of this issue is to design and implement a visually appealing and user-friendly Sign-up UI.

## Acceptance Criteria:
- [ ] The login form is displayed correctly on the page
- [ ] The form fields and submit button are functional and handle user input correctly
- [ ] Error messages are displayed correctly when invalid credentials are entered
- [ ] The social login buttons are displayed 
- [ ] The UI is responsive and works well on different mobile screen sizes

_**Note:**_ _For now, we're only focusing on creating the design UI for mobile view. We'll address the desktop view in a future iteration._
Attachments:

![Image](https://github.com/user-attachments/assets/23ac4eae-192a-4ed8-8029-3cbe36f5cb76)

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-wallet-app) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/design/UjbBQIFKATd1DisTBRsMdd/Test-Project?node-id=29-9854&t=9h97AC3WcxkziHnS-0)
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by dadiorchen** [comment]
So this is about UI, not includes the real logic to handle the login logic? right?

**Comment by pierrelstan** [comment]
@dadiorchen  This is about the UI, and does not include the real logic.

**Comment by cihanbagriyanik** [comment]
I can do that too?

**Comment by pierrelstan** [comment]
@cihanbagriyanik yes, you can.
