### ISSUE TITLE
Loading UI Design

### ISSUE THREAD

**Issue by pierrelstan** [Greenstand/treetracker-wallet-app#220]
# Description:
We need to design and implement a loading UI component for the creating account process and Login process. The goal is to provide a seamless user experience by displaying a progress bar and a subtitle that informs the user that their request is being processed.
## Acceptance Criteria:
- [ ] The loading UI is displayed immediately after the user submits the form.
- [ ] The loading UI includes a progress bar that animates to indicate that the account creation process is in progress.
- [ ]  a subtitle that says "Creating an account, please wait".
- [ ] The loading UI is displayed for a reasonable time (e.g. 2-3 seconds) before the user is redirected to the next step.

**Dependency:** _This issue is dependent on the completion of the "Implement Sign up UI Design for Web #216"  and " Implement Web Login UI design #219 " issues. The loading UI will be displayed after the user submits the sign-up form, so the sign-up UI must be designed and implemented first._

**Note:** _For now, we're only focusing on creating the design UI for mobile view. We'll address the desktop view in a future iteration._

![Image](https://github.com/user-attachments/assets/c168f3b9-03d8-4fdc-a04e-753a55c5c12c)

![Logging in](https://github.com/user-attachments/assets/5cee1530-0fa2-4aaa-82b6-e7b1ebca148f)

Some hints:

Please read our [readme](https://github.com/Greenstand/treetracker-wallet-app) for more information/guide/tutorial.
For design guidelines checkout our [Figma design](https://www.figma.com/design/UjbBQIFKATd1DisTBRsMdd/Test-Project?node-id=29-9854&t=9h97AC3WcxkziHnS-0)
Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
To know more about our organization, visit our [website](https://greenstand.org/).
If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by ShubhamJumde94** [comment]
Hello, I'm Shubham and I'm interested in handling this task. I looked up the dependency as well and it would be nice if I can get a shot at the whole flow. I'm open to discussing this further. Thank you
- Shubham
