### ISSUE TITLE
Fix incorrect package names in transpilePackages

### ISSUE THREAD

**Issue by pierrelstan** [Greenstand/treetracker-wallet-app#227]
In the web app (apps/web) fix incorrect package name in transpilePackages within next.config.mjs to resolve transpilation issues.

Add demo-core to core package.

Some hints:

Please read our [readme](https://github.com/Greenstand/treetracker-wallet-app) for more information/guide/tutorial.
For design guidelines checkout our [Figma design](https://www.figma.com/design/UjbBQIFKATd1DisTBRsMdd/Test-Project?node-id=29-9854&t=9h97AC3WcxkziHnS-0)
Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
To know more about our organization, visit our [website](https://greenstand.org/).
If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by YashrajKupekar17** [comment]
I would like to solve this issue. Please assign it to me.

**Comment by Ansh2004P** [comment]
I would also like to solve this issue

**Comment by pierrelstan** [comment]
@YashrajKupekar17, are you working on this?

**Comment by pierrelstan** [comment]
@Ansh2004P Are you still interested in working on this?

**Comment by Ansh2004P** [comment]
Yes

**Comment by pierrelstan** [comment]
@Ansh2004P feel free to reach out if you need help
