### ISSUE TITLE
Add Header with Search Input for the Home Page

### ISSUE THREAD

**Issue by pierrelstan** [Greenstand/treetracker-wallet-app#267]
**Issue:** Focused on the web Next.js app.
**Description:**
We need a header for the home page that includes a logo, title, and search input field with an icon. This header will enhance user experience by providing easy access to the search functionality, allowing users to quickly search for content(name, company, wallet).

This issue focuses on adding the following components:
- logo 
- title 
- A search icon integrated within the input field.

**Hints:**
Please review the login and signup pages to see how similar components are structured and styled for consistency.

**Design Reference:**
You can find the design and placement details in the [Figma file here](https://www.figma.com/design/UjbBQIFKATd1DisTBRsMdd/Wallet-Management-System?node-id=739-9109&node-type=canvas&t=iqEwJQP58F3Dm899-0).

**Note:**
Feel free to start working on this issue right away—you don’t need to wait to be assigned. The first completed pull request will be prioritized for review and considered for acceptance. If you have any questions or need help with design specifics, please reach out!

![Image](https://github.com/user-attachments/assets/7c19460a-e7d8-4f88-b6b4-8e8edf677588) ![Image](https://github.com/user-attachments/assets/2d312d7e-2a2b-47a8-8524-501ef4e1cde8)

**Comment by kshitij79** [comment]
I would like to work on this issue and implement the header for the home page. 
I'am currently ensuring consistency by reviewing the login and signup pages in Figma file. 

Please let me know if there are any additional guidelines or specifics to consider.

**Comment by pierrelstan** [comment]
Hi @kshitij79, Thank you for taking the initiative to work on this issue! Please focus on the "Wallet App Iteration 1" design files to ensure alignment with our design goals. If you have any questions, feel free to reach out.

**Comment by kshitij79** [comment]
Hi @pierrelstan, I raised this PR: https://github.com/Greenstand/treetracker-wallet-app/pull/280 . I might be making some minor UI changes, but please let me know if you notice any bad coding practices or other concerns. I’ll make sure to incorporate those as well. Thanks!
