### ISSUE TITLE
Add bottom Navigation

### ISSUE THREAD

**Issue by pierrelstan** [Greenstand/treetracker-wallet-app#268]
**Issue:** Focused on the web Next.js app.

**Description:**
create a bottom navigation bar for the home page. This navigation bar will contain buttons for easy access to the Home, Send, and Settings pages.

**Hints:**
Please review the login and signup pages to see how similar components are structured and styled for consistency.

**Design Reference:**
You can find the design and placement details in the [Figma file here](https://www.figma.com/design/UjbBQIFKATd1DisTBRsMdd/Wallet-Management-System?node-id=739-9109&node-type=canvas&t=iqEwJQP58F3Dm899-0).

**Note:**
Feel free to start working on this issue right away—you don’t need to wait to be assigned. The first completed pull request will be prioritized for review and considered for acceptance. If you have any questions or need help with design specifics, please reach out!

![Image](https://github.com/user-attachments/assets/7d5678e9-e1c7-4250-9949-a7fba18232c2)![Image](https://github.com/user-attachments/assets/6e353a15-e8b5-461a-b737-4b73b1733c33)

**Comment by yuriBaza23** [comment]
Hi, I'm going to start working on this issue

**Comment by Seiyaroo** [comment]
Hi there @pierrelstan I was looking to get started and try to contribute but ran into some issues upon starting the project. I'm working on Windows OS, and get this error

![image](https://github.com/user-attachments/assets/b1957e39-6ced-4b76-9081-9d1b8b55cb29)

I've tried both Android Studio version Ladybug 2024.2.1 Patch 1, and WEbstorm 2024.2.4, and both get the same error found above even after running a clean install with Yarn install. I am likely doing something wrong, but wanted to check in and see if this is a bug with an upgrade to something internally version wise.

**Comment by pierrelstan** [comment]
Hi @Seiyaroo , 
try these steps to resolve the issue:

1. Delete all node_modules folders from the root, web, native, and core directories.
2. Delete the .expo folder from the native directory.
3. Run yarn in the root directory to install all the packages.
4. Run yarn start (native folder)

Let me know if it works or not.

**Comment by Seiyaroo** [comment]
@pierrelstan Looks like I still get this error after the above attempted fix.

![image](https://github.com/user-attachments/assets/10c33304-f277-41d0-8810-f3a300f3999e)

I do have a blank page though

![image](https://github.com/user-attachments/assets/5046606a-cd24-427e-9fcd-2b63aa105bc7)

Is a blank page expected behavior at this point? I'd imagine there would be some basic scaffolding or templated thing out but not sure. Maybe I *am* seeing things correctly?

**Comment by pierrelstan** [comment]
@Seiyaroo  Did you get the same error on the Android emulator?

**Comment by Seiyaroo** [comment]
@pierrelstan Same result, blank page clean yarn run to install everything.

I'm at the following point in the structure when I run yarn start

**Comment by pierrelstan** [comment]
@Seiyaroo Could you share the error from the Android emulator? It would help me get a better idea of what’s going wrong.

**Comment by pierrelstan** [comment]
@Seiyaroo Try updating the main branch with the latest changes and follow the steps I suggested.

**Comment by Seiyaroo** [comment]
Sorry had to dinner @pierrelstan So this is in android studio

![image](https://github.com/user-attachments/assets/d8762008-1b55-4197-b551-955d06e4aafa)

Fresh clean install of everything, even deleted the folder / clone and made sure to start fully fresh. Still get a blank white page. At this point I think it's me but I don't know enough to really say hah

**Comment by pierrelstan** [comment]
@Seiyaroo, Could you please sync your main branch with the latest changes from  upstream/main?

**Comment by Seiyaroo** [comment]
@pierrelstan 
![image](https://github.com/user-attachments/assets/6477e86c-22d6-440e-8a76-ffc704d328aa)

White screen once loaded via android studio. Error below is shown up in both Android Studio and Webstorm.

![image](https://github.com/user-attachments/assets/0cfa085e-3832-4cf8-8be3-ea36ec09cfc5)

**Comment by pierrelstan** [comment]
Let's try one last attempt to resolve the issue:

1. Delete all node_modules folders from the root, web, native, and core directories.
2. Delete the .expo folder from the native directory.
3. Run yarn in the root directory to install all the packages.
4. Run yarn start (native folder).

If the issue persists, let's schedule a Slack meeting to troubleshoot further.

**Comment by Seiyaroo** [comment]
@pierrelstan Same issue unfortunately. Definitely would love to set up some time!

**Comment by pierrelstan** [comment]
@Seiyaroo Update your main branch with the latest changes and then, go through the steps I previously suggested.

**Comment by kshitij79** [comment]
Hi @pierrelstan ,
I have raised the PR for the bottom navigation bar feature. Please review it at your convenience: [PR #300](https://github.com/Greenstand/treetracker-wallet-app/pull/300).
