### ISSUE TITLE
Remove Header from Login and Signup Pages

### ISSUE THREAD

**Issue by pierrelstan** [Greenstand/treetracker-wallet-app#295]
Currently, the header appears on both the login and signup pages. We need to remove the header from these pages.
  
Attachments: [Figma file](https://www.figma.com/design/UjbBQIFKATd1DisTBRsMdd/Test-Project?node-id=29-9854&t=9h97AC3WcxkziHnS-0)

![Screenshot from 2024-12-11 17-36-54](https://github.com/user-attachments/assets/d5a97360-f57e-487e-b447-1ff320476e2d)

Some hints:
- Please read our [readme](https://github.com/Greenstand/treetracker-wallet-app) for more information/guide/tutorial.
- For design guidelines checkout our [Figma design](https://www.figma.com/design/UjbBQIFKATd1DisTBRsMdd/Test-Project?node-id=29-9854&t=9h97AC3WcxkziHnS-0)
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by kshitij79** [comment]
Raised this pr here: https://github.com/Greenstand/treetracker-wallet-app/pull/308
