### ISSUE TITLE
Integration the first page.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-wallet-app#45]
<img width="1440" alt="Screen Shot 2021-09-04 at 4 07 30 PM" src="https://user-images.githubusercontent.com/5744708/132087687-7d017a57-e11f-4976-a529-92887b9c8895.png">

**Comment by dadiorchen** [comment]
Prerequisites: #35 #26 #27

**Comment by dadiorchen** [comment]
API: #24

**Comment by dadiorchen** [comment]
https://www.loom.com/share/a4694833ed0f4700a448f68d4bdcde68

**Comment by CalDev98** [comment]
I work on this.

**Comment by dadiorchen** [comment]
Greay @CalDev98 please also refer to this PR, I have done some work on it: https://github.com/Greenstand/treetracker-wallet-web/pull/125

**Comment by CalDev98** [comment]
alright
